### ISSUE TITLE
Have users install yapf instead

### ISSUE THREAD

**Issue by mixxorz** [jason-kane/PyYapf#1]
Why do you have to make yapf run with Sublime's Python? I think it would be a better idea to just ask users to install yapf separately, like most formatting extensions for sublime.

Just my 2c. :smile:

**Comment by jason-kane** [comment]
I totally agree.  Yapf is designed to work nicely as an API but I didn't think it would need so many changes to get it running in 2.6  As-is this isn't maintainable.  It's all good, easy enough to fix. :)

**Comment by jason-kane** [comment]
Done; though I should still add a config option for the path to yapf
