### ISSUE TITLE
Does not work in Windows

### ISSUE THREAD

**Issue by maks-a** [jason-kane/PyYapf#14]
I'm using SublimeText 3 build 3083 and yapf (v.0.6.2).
Installed PyYapf through Package Control.
Than on any python file press 'ctrl+alt+f' or use 'PyYapf: Reformat Python' in command palette - nothing happens.

**Comment by jason-kane** [comment]
@catch22 just added some changes that should improve windows support (among other things).  Try again in a few days and post the last 50-ish lines of your sublime console after you try to reformat something.  It should include an error message of some sort so I have something to go on.
