### ISSUE TITLE
Editor puts you at the top of the file upon reformat

### ISSUE THREAD

**Issue by catch22** [jason-kane/PyYapf#19]
The culprit is likely b4a5a6087cef0144d7dd5f0b4a8991bd00fc09db. How about adding this back in when running under Sublime Text 2? (It is no necessary and in fact leads to some annoying recentering when using Sublime Text 3.)

**Comment by catch22** [comment]
This turned out to be a bit more complicated than anticipated. The implementation in the `PreserveView` context manager is a bit hackish, let me know if you have ideas :smile:

**Comment by jason-kane** [comment]
Much better than the old solution, hackish or otherwise.
