### ISSUE TITLE
UnicodeEncodeError when formatting py file

### ISSUE THREAD

**Issue by ipfans** [jason-kane/PyYapf#20]
When I trying to format python file contains Chinese words like '你好', pyyapf will raise error:

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 689-694: ordinal not in range(128)
```

But it will works fine with yapf command like:' yapf -i [filename]'.

Just like this case:

```python

#!/usr/bin/env python
# coding=utf-8

print(u"你好")

```

debug log:

```
PyYapf: Encoding is 'UTF-8'
PyYapf: Formatting selection (0, 1671)
PyYapf: Detected indent ''
PyYapf: Running ['/Users/user/.pyenv/versions/2.7.11/bin/yapf', '--verify'] in /Users/user/project/tests
PyYapf: Exit code 1
PyYapf: Error:
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/2.7.11/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/Users/user/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/__init__.py", line 250, in run_main
    sys.exit(main(sys.argv))
  File "/Users/user/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/__init__.py", line 155, in main
    sys.stdout.write(reformatted_source)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 689-694: ordinal not in range(128)

error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 689-694: ordinal not in range(128)
```

**Comment by jason-kane** [comment]
Thank you for including the debug log.  What encoding is the file opened with in Sublime?  As I recall it is passed through to yapf as an environmental.

view.encoding() in the console should tell you.

**Comment by jason-kane** [comment]
nevermind, I have reproduced the problem.

**Comment by jason-kane** [comment]
We are hitting this yapf defect:

https://github.com/google/yapf/pull/145

**Comment by jason-kane** [comment]
If you replace your PyYapf.py with:

https://github.com/jason-kane/PyYapf/blob/dont-use-stdin/PyYapf.py

It will probably work, your example failed for me in exactly the same way but works properly after this change.

It isn't a very elegant way to go about it but until https://github.com/google/yapf/pull/145 is resolved this isn't such a horrible way to go.  I'll see about merging into master and issuing another release tomorrow; I'd like to sleep on it.

**Comment by catch22** [comment]
Interesting. I didn't catch this error since I am running yapf with Python 3.

**Comment by ipfans** [comment]
@jason-kane can you give more detail about filepath of this file

**Comment by catch22** [comment]
It should be in `<Data>/Packages/PyYapf Python Formatter/PyYapf.py` where `<Data>` depends on your operating system, see [here](http://docs.sublimetext.info/en/sublime-text-3/basic_concepts.html#the-data-directory).

**Comment by ipfans** [comment]
@catch22 it's strange that I can not find it at ```~/Library/Application Support/Sublime Text 3/Packages```.

```
➜  /  find . 2>&1 |grep -i "PyYapf.py"
```

still nothing found

**Comment by catch22** [comment]
Are you using OS X? This is somewhat bizarre :confused:

**Comment by ipfans** [comment]
@catch22 It seems that ST3 PackageControl will compress package to ```Installed Packages``` dir.

@jason-kane debug log:

```
reloading plugin PyYapf Python Formatter.PyYapf
INFO:root:Registering handler with address ('localhost', 56244)
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/PyYapf Python Formatter/PyYapf.py", line 382, in run
    Yapf(self.view).format(s, edit)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/PyYapf Python Formatter/PyYapf.py", line 243, in format
    encoded_output = h.read()
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 464: ordinal not in range(128)
INFO:root:Registering handler with address ('localhost', 56299)
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/PyYapf Python Formatter/PyYapf.py", line 382, in run
    Yapf(self.view).format(s, edit)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/PyYapf Python Formatter/PyYapf.py", line 243, in format
    encoded_output = h.read()
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 464: ordinal not in range(128)
```

**Comment by jason-kane** [comment]
I'll try it out in osx, figure out what is wrong and push a release in a
few hours.

**Comment by jason-kane** [comment]
more of a pain than I anticipated but not too horrible.  I have this example doc working in osx/st3 and linux/st2.  I've issued a release, it should propagate to package control in the next few hours.

**Comment by catch22** [comment]
good stuff. btw, i can test yapf running under python 3 with linux&win and st2&st3. it seems like you are running yapf under python 2, so this should cover most bases.

**Comment by catch22** [comment]
As a pragmatic way to catch future regressions, how about we add some Chinese characters to PyYapf.py? ;)

**Comment by jason-kane** [comment]
The upstream bug was fixed a few months ago (oct 24, 2017 actually); we should be able to switch to use_stdin and get rid of all the tempfile cruft.  I'll take a look when I get a few cycles.
