### ISSUE TITLE
EOF in multi-line statement

### ISSUE THREAD

**Issue by sametmax** [jason-kane/PyYapf#24]
Trying to run yapf on the selection : 

    (1, 2
     )

 And I get:
    lib2to3.pgen2.tokenize.TokenError: ('EOF in multi-line statement', (2, 0))

**Comment by catch22** [comment]
I'm afraid I cannot reproduce - which version of Sublime and Yapf are you using?

**Comment by sametmax** [comment]
yapf 0.6.2
subl 3114 (linux 64bits)

**Comment by catch22** [comment]
I am running the same sublime but a later yapf (0.11.0).

**Comment by jason-kane** [comment]
This looks like an upstream error; if you still see a similar message after upgrading to latest yapf verify that you get the same error on the command line (you almost certainly will) and leave a suitable message on the yapf board.  If it is a problem in pyyapf I'm happy to take a look, it just doesn't seem plausible.
