### ISSUE TITLE
Error running in Win10 Sublime Text 3

### ISSUE THREAD

**Issue by yyuekirin** [jason-kane/PyYapf#31]
When I press Ctrl-Alt-F to format the current selection, I got this.

OSError:[WinError 2] The system cannot find the file specified
You may need install YAPF and/or configure 'yapf_command' in PyYapf's Setting.

I have pip installed Yapf.

Thanks

**Comment by catch22** [comment]
Is yapf accessible in your PATH? Try setting the `yapf_command` option to point to your yapf binary.

**Comment by yyuekirin** [comment]
fix it! Thank you!

**Comment by nickbenzoni** [comment]
@catch22 how do I do that?
