### ISSUE TITLE
Support for setup.cfg or .style.yapf?

### ISSUE THREAD

**Issue by srcreigh** [jason-kane/PyYapf#36]
Hi, I am trying to set up a project-level yapf config but PyYapf doesn't seem to recognize the `setup.cfg` file at the root of the project. I would expect it to search for a `setup.cfg` file starting from where the file is located. In my case it is something like `$PATH_TO_PROJ/setup.cfg` and `$PATH_TO_PROJ/module/data/suggestions.py`.

**Comment by catch22** [comment]
Hey. In principle this should get picked up, since we are running yapf in the directory of the current file (for that very reason). I wonder what goes wrong...

**Comment by catch22** [comment]
Does yapf pick up your config correctly when you launch it manually on the command line from the `$PATH_TO_PROJ/module/data` directory?

**Comment by jason-kane** [comment]
I would also check to see if there is a $PATH_TO_PROJ/module/setup.cfg that would prevent it from finding the one you really want.

**Comment by jgirardet** [comment]
I have the same probleme. yapf is ok in command line. but pyapf doesn't find my setup.cfg

**Comment by jason-kane** [comment]
Which os, sublime version and yapf version?  If I have a similar setup available I can try to reproduce.

**Comment by ghostku** [comment]
Same problem:
- Windows 10 1709
- Sublime Text 3 3143
- YAPF 0.20.2

.style.yapf file used with yapf command but ignored by PyYAPF.

**Comment by catch22** [comment]
Aha, I have a hunch... can you try setting `use_stdin` to `true` in the PyYapf configuration file?

I think we knew this once according to the comment in https://github.com/jason-kane/PyYapf/blob/master/PyYapf.sublime-settings#L158 😃

**Comment by jason-kane** [comment]
Excellent; it needs some verification but I believe we can make that the default (or even the only approach) since the upstream bug that required it is (in theory) resolved.

**Comment by catch22** [comment]
Let's leave this issue open until we have released a new version.

**Comment by jason-kane** [comment]
Pushing the new version tonight; sorry I took so long.
