### ISSUE TITLE
Support for `# yapf: disable`

### ISSUE THREAD

**Issue by michaelwooley** [jason-kane/PyYapf#37]
Hi,

It would be great if PyYapf supported the ability to disable/ignore lines of code. Here's one that I've run into:

    c = {**a, **b} # yapf: disable
Non-support for dictionary unpackking in YAPF was already reported [here](https://github.com/google/yapf/issues/233). The next best alternative seems to be to disable these lines. However, it does not seem that PyYapf acknowledges these disable commands.

Thanks for the great plugin!

**Comment by jason-kane** [comment]
That is sure odd, we are quite literally dumping the code into yapf.  Let me see if I can reproduce.. huh.  If I run pyyapf document on:
```
a = 1
b =  2

c = {**a, **b} # yapf: disable

d = {**a, **b}
```
it fixes the double space on 'b', but doesn't touch either `c =` or `d =`.  Maybe yapf version?  ```$ yapf -v
yapf 0.21.0
``` Is this a valid way to reproduce the issue?  (confused)

**Comment by michaelwooley** [comment]
Good thought on the version. I was on 0.20.1 but have now updated to 0.21. However, the upgrade didn't touch the YAPF command in `/usr/local/bin/yapf`. I guess I just need to figure out how to upgrade that particular file.

**Comment by catch22** [comment]
Try `cat /usr/local/bin/yapf` to determine which Python installation it was installed with.

**Comment by michaelwooley** [comment]
I've found the yapf file. I'm confused about how to get it to update.

**Comment by jason-kane** [comment]
`pip install --upgrade yapf` and/or `pip3 install --upgrade yapf` will generally do the trick.  In any case this looks like a yapf issue, not a plugin problem.
