### ISSUE TITLE
PyYapf not working: AttributeError: 'ParseError' object has no attribute 'message'

### ISSUE THREAD

**Issue by romanovzky** [jason-kane/PyYapf#39]
Hi there,

I'm failing to get PyYapf to work. The python package is installed globally, and on sublime I have non-cosmetic packages related to python:

- Anaconda
- AutoPEP8
- Djaneiro
- SublimeLinter
- SublimeLinter-flake8

How can I further debug? Cheers

**Comment by jason-kane** [comment]
You'll want to set the yapf_command setting to point at your yapf executable.  I'm thinking over ways to simplify the initial setup but that is how it works right now.

**Comment by jason-kane** [comment]
https://github.com/jason-kane/PyYapf/pull/41 gives us an easy way to address this, it would be helpful if you told us where your yapf binary is installed.

**Comment by jason-kane** [comment]
the 'new' search feature will be included in the next release (this weekend), that should take care of the most common sublime-cant-find-yapf problems.

**Comment by jason-kane** [comment]
Okay, should be addressed in v0.14.1.  Please post again if it does work (or to confirm it does).  It will be a few hours before the new code shows up in sublime Package Control.
