### ISSUE TITLE
ST3 error in Ubuntu 18.04

### ISSUE THREAD

**Issue by casajake** [jason-kane/PyYapf#40]
OSError: [Errno 2] No such file or directory: '/usr/local/bin/yapf'

You may need to install YAPF and/or configure 'yapf_command' in PyYapf's Settings.
***********************
I corrected this by finding yapf in /usr/bin/yapf3 and putting the path in the user settings.
Otherwise, great program! Thanks for taking the time to write it.

**Comment by jason-kane** [comment]
I do think adding some if os.path.exists(...) to find yapf in the most common locations would save people some initial grief.  I'm not sure about a good way to persist the results of the search so we don't have to re-do it but that should be solve-able.

**Comment by jason-kane** [comment]
https://github.com/jason-kane/PyYapf/pull/41  should address this specific issue (ubnt 18.04, yapf3) but I assume there are other common install locations I'm missing.
