### ISSUE TITLE
Sublime 3 plug-in issue with macOS 10.13.6 

### ISSUE THREAD

**Issue by dsthrower** [jason-kane/PyYapf#42]
Hello,

I have installed and can see the PyYapf package in both the sublime installed packages and packages file (screen shots attached) and the error when I try the key command.  I am sure this is super simple.  I assume I need to point the "yapf command:" to the right place, but not sure if I am right as I can't get it quite right.

Thanks and sorry for what is a silly question, but the demo I saw of PyYapf looked awesome so I would really like to get it work

<img width="772" alt="screen shot 2018-07-19 at 9 45 43 pm" src="https://user-images.githubusercontent.com/40488075/42983777-5c747c68-8b9d-11e8-8813-24961a69d4cc.png">
<img width="712" alt="screen shot 2018-07-19 at 9 48 20 pm" src="https://user-images.githubusercontent.com/40488075/42983793-8198f85c-8b9d-11e8-9727-1a4b4bd0d6ff.png">
<img width="609" alt="screen shot 2018-07-19 at 9 49 18 pm" src="https://user-images.githubusercontent.com/40488075/42983811-a3c137c8-8b9d-11e8-9255-a28dc323c286.png">

**Comment by jason-kane** [comment]
Do you have yapf installed?  I suspect that is the primary issue.

**Comment by dsthrower** [comment]
I do.  I pip installed yapf.  I then went into pyyapf and tried to point
yapf command to the yapf directory, but received an error.  Screen shots of
error, pyyapf settings file and directory tree with yapf attached.

Thank you!

**Comment by gzeng** [comment]
@dsthrower did you pip install in virtual env? If so, you need to update yapf config accordingly. this fixed my issue `"yapf_command": "venv/bin/yapf"`.

**Comment by jason-kane** [comment]
the 'new' search feature will be included in the next release (this weekend), that should take care of the most common sublime-cant-find-yapf problems.

**Comment by jason-kane** [comment]
Okay, should be addressed in v0.14.1.  Please post again if it does work (or to confirm it does).  It will be a few hours before the new code shows up in sublime Package Control.
