### ISSUE TITLE
Adaption in Sublime text 2

### ISSUE THREAD

**Issue by ariswang92** [jason-kane/PyYapf#53]
In line 205 of PyYapf.py, it asks for sublime.expand_variables while such API is only available in sublime text 3
In line 12 of PyYapf.sublime-settings, the comma inside the bracket should be removed.

**Comment by jason-kane** [comment]
Thank you, I’ll check it out.

**Comment by jason-kane** [comment]
Addresses in https://github.com/jason-kane/PyYapf/commit/201575f6152597276843b6b4b76d6c7489784130 ; the comma thing shouldn't matter but I don't particularly care so I changed it anyway.  I'll verify the plugin is still working then cut a release.
