### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by rahulthewaffle** [jason-kane/PyYapf#55]
Hi,

Of the three "mentions" links in the readme:
Must-Have Packages and Settings in Sublime Text for a Python Developer
Teach yapf and python-fire to Python beginners
Yapf - we brush the code of Python with autocorrector

The first one redirects to a probably malicious site (guessing the domain changed/expired), and the second and third are broken.

Cheers!

**Comment by jason-kane** [comment]
:(  ah well, I’ll clean it up.

**Comment by jason-kane** [comment]
done, thank you.
