### ISSUE TITLE
Set an option to run yapf on .py file save

### ISSUE THREAD

**Issue by sametmax** [jason-kane/PyYapf#9]
This way you can run yapf without thinking about it. This option should set to false by default though.

**Comment by sametmax** [comment]
Is it just a command, or is there a onSave hook added too ?

**Comment by jason-kane** [comment]
There is a pre-save hook controlled by the "on_save" setting; it should take a boolean value.  The default config file will need a little love to properly cover all valid options.

**Comment by sametmax** [comment]
Thanks

**Comment by catch22** [comment]
Check out `Preferences -> Package Settings -> PyYapf -> Settings - Default` for a list of all options (and best configure them in `Preferences -> Package Settings -> PyYapf -> Settings - User`). We should add some better documentation in the README :smile:
